### ISSUE TITLE
Extremly helpful tool!

### ISSUE THREAD

**Issue by Fronix** [kaermorchen/meiliadmin#18]
Just wanted to let you know that this saved me tons of time not having to develop my own little adminpanel. Love the tool, does exactly what it advertises and was really simple to deploy!

Some ideas:

- ~Would be nice to be able to manange API keys~ Edit: Just noticed that key management was already implemented
- Would love if I could change all index settings in one go, on top of specific settings.

**Comment by kaermorchen** [comment]
Hi! Thanks.

> Would love if I could change all index settings in one go, on top of specific settings.

Yeah, I can do it.

**Comment by kaermorchen** [comment]
Done in 0.2.0.

I've closed the issue, but feel free to reopen it (or create new one) if you will need another feature.
