### ISSUE TITLE
Missing property error

### ISSUE THREAD

**Issue by Kabingeran** [kaermorchen/meiliadmin#33]
Hi
I see a validation bug or something is wrong here https://nimb.ws/7fhpjT ?

**Comment by kaermorchen** [comment]
Hi.

Look like, your test index has primaryKey `1` and the validation shows error about it. 

I have added an empty primaryKey in new document by default in release `0.4.3`

**Comment by Kabingeran** [comment]
Will it be possible to add many documents through the interface at one time?

**Comment by kaermorchen** [comment]
> Will it be possible to upload several documents at once through the interface?

Added in latest release `0.5.0`
