### ISSUE TITLE
Index name and field names should not accurate, not title-cased/capitalized

### ISSUE THREAD

**Issue by tacman** [kaermorchen/meiliadmin#61]
In the dashboard, the index name is title-cased.  It shouldn't be, as a programmer using that name to get the index may get an error.

If the programmer wants to capitalize the index names, they should, but the UI should display the actual name of the index, not formatted in any way.

![image](https://github.com/kaermorchen/meiliadmin/assets/619585/15ccca34-18f9-4cd8-a45b-f795743ce5d2)

The column names should be exactly the same as the data keys:

![image](https://github.com/kaermorchen/meiliadmin/assets/619585/9ace94bf-8c11-41bc-b3bc-8f3b2d2ec27c)

**Comment by kaermorchen** [comment]
Fixed in latest realese
